# Auto-generated remote state configuration for app/
# Generated by './init-terraform.sh' from infra/backend.tfbackend

infra_state_bucket = "terraform-state-577064425254"
infra_state_key    = "PropHero-Tech/sequin/infra/terraform.tfstate"
infra_state_region = "ap-southeast-2"
aws_region         = "ap-southeast-2"

